packages:
  - packages/*

catalog:
  # Core Dependencies
  typescript: ^5.8.3
  commander: ^12.0.0
  chalk: ^5.3.0
  inversify: ^7.5.1
  reflect-metadata: ^0.2.2
  
  # Build Tools
  vite: ^6.0.7
  vite-plugin-dts: ^4.3.0
  
  # Development Dependencies
  vitest: ^3.2.4
  tsx: ^4.20.3
  
  # Node.js Types
  "@types/node": ^24.0.12
  
  # Build & Linting
  markdownlint-cli2: ^0.18.1

catalogMode: prefer