packages:
  - packages/*
  - apps/*

catalog:
  '@modelcontextprotocol/sdk': ^1.16.0
  '@pnpm/catalogs.config': ^1000.0.3
  '@pnpm/exportable-manifest': ^1000.1.2
  '@pnpm/find-workspace-packages': ^6.0.9
  '@pnpm/logger': ^1001.0.0
  '@pnpm/workspace.read-manifest': ^1000.2.1
  '@types/node': ^24.0.15
  '@vitest/coverage-v8': ^3.2.4
  chalk: ^5.4.1
  commander: ^12.0.0
  inversify: 7.5.4
  markdownlint-cli2: ^0.18.1
  pino-pretty: ^13.0.0
  tsx: ^4.20.3
  typescript: ^5.8.3
  ulid: ^3.0.1
  vite: ^6.3.5
  vite-plugin-dts: ^4.5.4
  vitest: ^3.2.4

catalogMode: prefer
