packages:
  - packages/*

catalog:
  '@modelcontextprotocol/sdk': ^1.15.1
  '@types/node': ^24.0.12
  '@vitest/coverage-v8': ^3.2.4
  chalk: ^5.3.0
  commander: ^12.0.0
  inversify: ^7.5.1
  markdownlint-cli2: ^0.18.1
  tsx: ^4.20.3
  typescript: ^5.8.3
  vite: ^6.0.7
  vite-plugin-dts: ^4.3.0
  vitest: ^3.2.4

catalogMode: prefer
